### PR TITLE
Check that liblzma has `lzma_cputhreads()`, to fix Mac build failure. Fixes #102.

### LINKED ISSUE #102: Iostreams doesn't build on Mac
The Mac build on Travis fails with a link error caused by PR #95, but the job is marked as allowed failure due to an unrelated issue #91.

Whether liblzma contains the necessary MT functions should be checked by the Jamfile using `check-target-builds`. (Add a source file `has_lzma_cputhreads.cpp`, then add `[ check-target-builds has_lzma_cputhreads : : define=BOOST_IOSTREAMS_LZMA_NO_MULTITHREADED=1 ]` to `lzma-requirements`.

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by mclow** [comment]
I applied this patch locally (Mac OS 10.14.6), and got the following results:
```
$ ./b2 iostreams
warning: mismatched versions of Boost.Build engine and core
warning: Boost.Build engine (./b2) is 2018.02.00
warning: Boost.Build core (at /Sources/Boost/main/tools/build/src) is 4.0-git
Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)
    - zlib                     : yes
    - bzip2                    : yes
    - lzma                     : yes
    - zstd                     : no
    - symlinks supported       : yes (cached)
    - has_lzma_cputhreads builds : no
...patience...
...found 1667 targets...
...updating 7 targets...
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/file_descriptor.o
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/mapped_file.o
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/bzip2.o
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/gzip.o
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/lzma.o
clang-darwin.compile.c++ bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/zlib.o
clang-darwin.link.dll bin.v2/libs/iostreams/build/clang-darwin-10.0/debug/threading-multi/visibility-hidden/libboost_iostreams.dylib
...updated 7 targets...
```

LGTM.

**Comment by jbonyun** [comment]
@mclow: you're concluding that @pdimov's PR #103 fixes it for you on Mac? And that, using `check-lzma_cputhreads` means you don't also require the version change to 5.2.4 that you mentioned in the #102 thread? Because just the fact that 5.2.4 exists is news to me, and that it deletes a feature added in 5.2.0 is bothersome. So if @pdimov's changes solve it, that would be wonderful.

Do any of the Travis builds have `has_lzma_cputhreads = yes`? I couldn't see one. They're based on Xenial mostly, with a few Trusty. I believe they default to 5.1.1, so wouldn't have it automatically. Is adding a Bionic build (defaults to liblzma 5.2.2) a problem that we don't want to open up? I have no experience with Travis/etc.

**Comment by pdimov** [comment]
Should be possible to add a Bionic job to Travis; @jeking3?

**Comment by pdimov** [comment]
Here's a bionic run that reports "has_lzma_cputhreads builds: yes": https://travis-ci.org/boostorg/check_build/jobs/614060203

**Comment by jeking3** [comment]
@pdimov yes, updating the CI build to the current standards and adding a bionic job should be possible.

**Pull request merged**
