### PR TITLE
Fix for Ticket #11954

### PR DESCRIPTION
**Pull request by scopeInfinity**

### CODE REVIEW

**Comment by saturnjct** [comment]
Any chance that this change can make it into Boost 1.61.0?

**Comment by mattgodbolt** [comment]
+1 - the deprecation warnings are rather annoying in our otherwise-warning-free code.

**Comment by bc-lee** [comment]
Well, It hasn't fixed yet in Boost 1.61 :(.

**Comment by nigels-com** [comment]
$ patch -p0 < boost.patch

```
diff -ru type_traits.original/broken_compiler_spec.hpp type_traits/broken_compiler_spec.hpp
--- type_traits.original/broken_compiler_spec.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/broken_compiler_spec.hpp	2016-05-27 17:48:35.023137408 +1000
@@ -13,7 +13,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (boost/type_traits/broken_compiler_spec.hpp) is deprecated")
+//("NOTE: Use of this header (boost/type_traits/broken_compiler_spec.hpp) is deprecated")
 #endif
 
 #endif // BOOST_TT_CONFIG_HPP_INCLUDED
diff -ru type_traits.original/config.hpp type_traits/config.hpp
--- type_traits.original/config.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/config.hpp	2016-05-27 17:48:35.023137408 +1000
@@ -13,7 +13,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (boost/type_traits/config.hpp) is deprecated")
+//("NOTE: Use of this header (boost/type_traits/config.hpp) is deprecated")
 #endif
 
 #endif // BOOST_TT_CONFIG_HPP_INCLUDED
diff -ru type_traits.original/detail/bool_trait_def.hpp type_traits/detail/bool_trait_def.hpp
--- type_traits.original/detail/bool_trait_def.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/bool_trait_def.hpp	2016-05-27 17:49:04.646825359 +1000
@@ -15,7 +15,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
+//("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
 #endif
 
 #include <boost/type_traits/detail/template_arity_spec.hpp>
diff -ru type_traits.original/detail/ice_and.hpp type_traits/detail/ice_and.hpp
--- type_traits.original/detail/ice_and.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/ice_and.hpp	2016-05-27 17:49:04.646825359 +1000
@@ -15,7 +15,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (ice_and.hpp) is deprecated")
+//("NOTE: Use of this header (ice_and.hpp) is deprecated")
 #endif
 
 namespace boost {
diff -ru type_traits.original/detail/ice_eq.hpp type_traits/detail/ice_eq.hpp
--- type_traits.original/detail/ice_eq.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/ice_eq.hpp	2016-05-27 17:49:04.646825359 +1000
@@ -14,7 +14,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (ice_eq.hpp) is deprecated")
+//("NOTE: Use of this header (ice_eq.hpp) is deprecated")
 #endif
 
 namespace boost {
diff -ru type_traits.original/detail/ice_not.hpp type_traits/detail/ice_not.hpp
--- type_traits.original/detail/ice_not.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/ice_not.hpp	2016-05-27 17:49:04.646825359 +1000
@@ -14,7 +14,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (ice_not.hpp) is deprecated")
+//("NOTE: Use of this header (ice_not.hpp) is deprecated")
 #endif
 
 namespace boost {
diff -ru type_traits.original/detail/ice_or.hpp type_traits/detail/ice_or.hpp
--- type_traits.original/detail/ice_or.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/ice_or.hpp	2016-05-27 17:49:04.650825317 +1000
@@ -14,7 +14,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (ice_or.hpp) is deprecated")
+//("NOTE: Use of this header (ice_or.hpp) is deprecated")
 #endif
 
 namespace boost {
diff -ru type_traits.original/detail/template_arity_spec.hpp type_traits/detail/template_arity_spec.hpp
--- type_traits.original/detail/template_arity_spec.hpp	2016-05-27 17:45:56.292804600 +1000
+++ type_traits/detail/template_arity_spec.hpp	2016-05-27 17:49:04.654825275 +1000
@@ -10,7 +10,7 @@
 // This header is deprecated and no longer used by type_traits:
 //
 #if defined(__GNUC__) || defined(_MSC_VER)
-# pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
+//("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
 #endif
 
 #   define BOOST_TT_AUX_TEMPLATE_ARITY_SPEC(i, name) /**/
```

**Comment by Kojoley** [comment]
Boost 1.62 will ship soon. Can we have this fix in it?

**Comment by nigels-com** [comment]
Indeed, it's a good window of opportunity.

**Comment by ishitatsuyuki** [comment]
Seems 71b4ed2 fixed this in a graceful way.

**Comment by Kojoley** [comment]
> Seems 71b4ed2 fixed this in a graceful way.

No, it was fixed with #24 merge, thanks to @turkanis for this.

**Pull request closed without merging**
