### PR TITLE
Turn off BOOST_IOSTREAMS_HAS_DINKUMWARE_FPOS for clang++

### PR DESCRIPTION
**Pull request by hia3**

### CODE REVIEW

**Comment by jeking3** [comment]
We should probably switch to Boost.Predef here and detect dinkumware itself...

**Comment by hia3** [comment]
I have two variants:

1. Similar to [this](https://github.com/boostorg/unordered/blob/develop/include/boost/unordered/detail/fwd.hpp#L32-L34).

    #include <boost/predef.h>
    ...
    // I have no idea when Dinkumware added it, probably a lot
    // earlier than this check.
    #if defined(BOOST_LIB_STD_DINKUMWARE) && (BOOST_LIB_STD_DINKUMWARE >= BOOST_VERSION_NUMBER(6, 50, 0))


2. Or:

    #include <boost/predef.h>
    ...
    #if defined(BOOST_LIB_STD_DINKUMWARE) && (_MSVC_STL_VERSION >= 141)

Trying to summon @BillyONeal

**Comment by BillyONeal** [comment]
Hi there, my original PR didn't guard for compiler at all. I think this is a library property and `_MSVC_STL_VERSION` should be sufficient to identify but some maintainers were unhappy with that...

**Comment by BillyONeal** [comment]
> We should probably switch to Boost.Predef here and detect dinkumware itself...

The difficulty here is that MSVC++'s standard library is a Dinkumware derivative but is no longer actually Dinkumware; so using a Dinkumware test to detect us will likely do the wrong thing on other Dinkumware licensees (e.g. I've heard rumors that Playstation still uses Dinkumware?).

**Comment by jeking3** [comment]
So `_CPPLIB_VER` identifies dinkumware, or a dinkumware derivitive, however we only want to set this `BOOST_IOSTREAMS_HAS_DINKUMWARE_FPOS` on MSVC if STL is version 140 or earlier, is that correct?  And the change here is that MSVC started shipping with clang support built-in, so this change accounts for that case which was missing?

**Comment by BillyONeal** [comment]
> BOOST_IOSTREAMS_HAS_DINKUMWARE_FPOS on MSVC if STL is version 140 or earlier, is that correct?

Right; other Dinkumware licensees likely still have the bigger-than-2-GiB file handling bugs we fixed.

**Comment by jeking3** [comment]
That's what I was thinking, but I wanted to clarify.  Thanks @pdimov!

**Comment by pdimov** [comment]
`_YVALS` is probably obsolete; I don't think we support pre-`_CPPLIB_VER` Dinkumware. Checking `__SGI_STL_PORT` or `_STLPORT_VERSION` seems redundant; I don't see how you can use both Dinkumware and STLport at the same time. Although who knows what happens on esoteric platforms. `__QNX__` and `__VXWORKS__` are probably checked because they use Dinkumware too? Not sure.

**Comment by pdimov** [comment]
https://github.com/boostorg/iostreams/pull/13 and https://github.com/boostorg/iostreams/pull/49 introduce the checks for VxWorks. Presumably QNX uses a similar Dinkumware version.

The STLPort checks come from https://github.com/boostorg/iostreams/commit/2d11830721a190083aeec1b937608738276492ee, without much of a history.

**Comment by pdimov** [comment]
Some more history: https://github.com/boostorg/iostreams/commit/3a18bc413223c80f584249782c01ab3da40da03e, https://github.com/boostorg/iostreams/commit/ccf854861c039a815315ddb8dd6fb3e3f6a5fd88

**Comment by ibrahimLearning** [comment]
@BillyONeal 
I installed boost with pcl. Now how can I turn off for making it usable in my project

**Pull request merged**
