### PR TITLE
Fix endless loop when writing to file exceeds quota.

### PR DESCRIPTION
**Pull request by rdoeffinger**
See also issue 2557.

### CODE REVIEW

**Comment by eldiener** [comment]
Maybe "quota_full_test.cpp" is a better name than "disk_full_test.cpp" for the test you added ? The latter name might be a bit disturbing to anyone who wants to run the iostream tests and does not want to think that one of them actually fills his hard disk with data so that there is no room left for other files on the hard disk.

**Comment by rdoeffinger** [comment]
I agree that the test name is not good, and maybe by what it tests now it should rather be called "write_failure_test" or such?
I don't really think that replacing "disk" by "quota" will be much comfort to anyone worrying :)
But if you have a strong preference for a specific name, I'm happy to just pick that.

**Comment by rdoeffinger** [comment]
Ok, updated. Btw the test system seems to have a pretty annoying bug: when aborting a test run with ctrl+c, none of the test binaries are actually aborted. So if you have a hanging test you have to go an manually kill it (after wondering why the computer got so slow)...

**Comment by eldiener** [comment]
The test system is a Boost Build issue. Please bring it up there if you like.

**Pull request merged**
